"""empty message

Revision ID: 7fc544e603f5
Revises: 231f361a9c4f
Create Date: 2018-01-23 21:02:55.698654

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7fc544e603f5'
down_revision = '231f361a9c4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vendas', 'id_venda',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('vendas', 'quantidade',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vendas', 'quantidade',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('vendas', 'id_venda',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
